"""Initial schema

Revision ID: 1efe8d14e8ae
Revises: 
Create Date: 2026-05-28 03:59:07.118629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '1efe8d14e8ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(length=500), nullable=False),
    sa.Column('back', sa.String(length=500), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'front', 'language', name='uq_card_user_front_lang')
    )
    op.create_index('idx_card_due', 'cards', ['user_id', 'last_reviewed', 'stability'], unique=False)
    op.create_index('idx_card_language', 'cards', ['user_id', 'language'], unique=False)
    op.create_index('idx_card_tags', 'cards', ['user_id', 'tags'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('obsidian_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_path', name='uq_note_user_path')
    )
    op.create_index('idx_note_due', 'obsidian_notes', ['user_id', 'last_reviewed', 'stability'], unique=False)
    op.create_index('idx_note_tags', 'obsidian_notes', ['user_id', 'tags'], unique=False)
    op.create_index('idx_note_user', 'obsidian_notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_obsidian_notes_id'), 'obsidian_notes', ['id'], unique=False)
    op.create_table('session_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('module_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('minutes_spent', sa.Integer(), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_date', 'module_type', 'category', name='uq_stats_unique')
    )
    op.create_index('idx_stats_user_date', 'session_stats', ['user_id', 'session_date'], unique=False)
    op.create_index(op.f('ix_session_stats_id'), 'session_stats', ['id'], unique=False)
    op.create_table('note_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['obsidian_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_embedding_note', 'note_embeddings', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_embeddings_id'), 'note_embeddings', ['id'], unique=False)
    op.create_table('obsidian_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_time', sa.DateTime(), nullable=True),
    sa.Column('stability_after', sa.Float(), nullable=True),
    sa.Column('difficulty_after', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('elapsed_days', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['obsidian_notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_obsidian_review_note', 'obsidian_reviews', ['note_id'], unique=False)
    op.create_index('idx_obsidian_review_user_date', 'obsidian_reviews', ['user_id', 'review_time'], unique=False)
    op.create_index(op.f('ix_obsidian_reviews_id'), 'obsidian_reviews', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_time', sa.DateTime(), nullable=True),
    sa.Column('stability_after', sa.Float(), nullable=True),
    sa.Column('difficulty_after', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('elapsed_days', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_card', 'reviews', ['card_id'], unique=False)
    op.create_index('idx_review_user_date', 'reviews', ['user_id', 'review_time'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.execute("DROP TABLE IF EXISTS card_tags CASCADE")
    op.execute("DROP TABLE IF EXISTS flashcard CASCADE")
    op.execute("DROP TABLE IF EXISTS review_log_entry CASCADE")
    op.execute("DROP TABLE IF EXISTS tag CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tag_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tag_pkey'),
    sa.UniqueConstraint('name', name='tag_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('review_log_entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flashcard_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('state_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcard.id'], name='review_log_entry_flashcard_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_log_entry_pkey')
    )
    op.create_table('flashcard',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('flashcard_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('front', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('back', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('elapsed_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scheduled_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lapses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='flashcard_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('card_tags',
    sa.Column('flashcard_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcard.id'], name='card_tags_flashcard_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='card_tags_tag_id_fkey'),
    sa.PrimaryKeyConstraint('flashcard_id', 'tag_id', name='card_tags_pkey')
    )
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index('idx_review_user_date', table_name='reviews')
    op.drop_index('idx_review_card', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_obsidian_reviews_id'), table_name='obsidian_reviews')
    op.drop_index('idx_obsidian_review_user_date', table_name='obsidian_reviews')
    op.drop_index('idx_obsidian_review_note', table_name='obsidian_reviews')
    op.drop_table('obsidian_reviews')
    op.drop_index(op.f('ix_note_embeddings_id'), table_name='note_embeddings')
    op.drop_index('idx_embedding_note', table_name='note_embeddings')
    op.drop_table('note_embeddings')
    op.drop_index(op.f('ix_session_stats_id'), table_name='session_stats')
    op.drop_index('idx_stats_user_date', table_name='session_stats')
    op.drop_table('session_stats')
    op.drop_index(op.f('ix_obsidian_notes_id'), table_name='obsidian_notes')
    op.drop_index('idx_note_user', table_name='obsidian_notes')
    op.drop_index('idx_note_tags', table_name='obsidian_notes')
    op.drop_index('idx_note_due', table_name='obsidian_notes')
    op.drop_table('obsidian_notes')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index('idx_card_tags', table_name='cards')
    op.drop_index('idx_card_language', table_name='cards')
    op.drop_index('idx_card_due', table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
